PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USER -q $POSTGRES_DB -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"';
PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USER -q $POSTGRES_DB -c 'CREATE EXTENSION IF NOT EXISTS "pgcrypto"';

